version: "3"
services:

  jenkins:
    build: ./
    privileged: true
    user: root
    ports:
      - "8080:8080"
    container_name: jenkins
    volumes: 
      - ./jenkins:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /bin/docker:/usr/bin/docker
